---
# tasks file for wordpress
    - name: Download WordPress.
      get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz validate_certs=no

    - name: Extract WordPress Archive
      unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html/ditelkin.com/public_html copy=no

    - name: Install unzip
      apt: pkg=unzip={{ unzip_version }} state=present

    - name: Copy Wordpress config file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - { src: "files/wp-config.php", dest: "/var/www/html/ditelkin.com/public_html/wordpress/wp-config.php" }
      notify:
        restart nginx

    - name: Copy theme TESSERACT on temp file
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "files/TESSERACT.zip", dest: "/tmp/TESSERACT.zip" }

    - name: Unarchive theme TESSERACT on wp-content file
      unarchive: src=/tmp/TESSERACT.zip dest=/var/www/html/ditelkin.com/public_html/wordpress/wp-content/themes remote_src=True
      notify:
        restart nginx

    - name: Make my wordpress content directory tree readable
      file:
        path: "/var/www/html/ditelkin.com/public_html/wordpress/"
        owner: www-data
        group: www-data
        mode: 0755
        recurse: yes
        state: directory
      notify:
        restart nginx

    - name: Start php7.0-fpm Service
      service: name=php7.0-fpm state=started enabled=yes